name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # pip install -r requirements-dev.txt  # (opcional) déjalo comentado

    - name: Prepare runtime folders
      run: |
        mkdir -p data/backups
        mkdir -p logs

    - name: Smoke test (import app and init DB)
      run: |
        python - <<'PY'
        # Verifica que la app importa y que la BD se inicializa sin errores
        from app.infra.db import get_connection
        with get_connection() as conn:
            conn.execute("PRAGMA foreign_keys = ON;")
        print("OK: DB disponible e inicializada")

        import app.streamlit_app as app_entry
        print("OK: app.streamlit_app importable")
        PY